---
- name: Fetch System Information from PAN-OS device
  hosts: all
  connection: local
  gather_facts: no
  
  collections:
    - paloaltonetworks.panos

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    provider:
      ip_address: '{{ ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
      port: '{{ mgmt_port | default("443") }}'
      api_key: '{{ api_key | default(omit) }}'

  tasks:
    - name: Gathering PAN-OS Facts
      paloaltonetworks.panos.panos_facts:
        provider: '{{ provider }}'
        gather_subset:
          - system
          - session
          - ha
          - interfaces
          - routing
          - vr
          - vsys

    - name: Show System Information
      debug:
        msg: '{{ ansible_facts }}'